# Generated by Django 5.1.7 on 2025-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced Beginner', 'Advanced Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
