# Generated by Django 5.1.7 on 2025-03-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
