# Generated by Django 5.1.7 on 2025-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='seats_available',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
